%{!?perl_prefix: %define perl_prefix %(eval "`%{__perl} -V:installprefix`"; echo $installprefix)}
%{!?perl_style: %define perl_style %(eval "`%{__perl} -V:installstyle`"; echo $installstyle)}

%define disttag pSPS

Name:           perl-AnyEvent-HTTP
Version:        1.4
Release:        1%{?dist}
Summary:        Simple but non-blocking HTTP/HTTPS client
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent-HTTP/
Source0:        http://www.cpan.org/modules/by-module/AnyEvent/AnyEvent-HTTP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(AnyEvent) >= 4.8
Requires:       perl

%description
This module is an AnyEvent user, you need to make sure that you use and run
a supported event loop.

%prep
%setup -q -n AnyEvent-HTTP-%{version}

%build
%{__perl} Makefile.PL INSTALL_BASE=%{perl_prefix}
make %{?_smp_mflags}

%install
%{__rm} -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{__mv} scripts $RPM_BUILD_ROOT/tmp

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
%{__rm} -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYING README
/usr/*
/tmp/*


%post
/tmp/./perl-AnyEvent-HTTP_post.sh
%{__rm} /tmp/perl-AnyEvent-HTTP_post.sh

%changelog
* Thu Jul 09 2009 Jason Zurawski 1.4-1
- Specfile autogenerated by cpanspec 1.78.
