%{!?perl_prefix: %define perl_prefix %(eval "`%{__perl} -V:installprefix`"; echo $installprefix)}
%{!?perl_style: %define perl_style %(eval "`%{__perl} -V:installstyle`"; echo $installstyle)}

%define disttag pSPS

Name:           perl-AnyEvent-HTTP
Version:        1.45
Release:        1.%{disttag}
Summary:        Simple but non-blocking HTTP/HTTPS client
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent-HTTP/
Source0:        http://www.cpan.org/modules/by-module/AnyEvent/AnyEvent-HTTP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(AnyEvent) >= 4.8
Requires:       coreutils
Requires:  perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
#
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:       perl(AnyEvent) >= 4.8

%description
This module is an AnyEvent user, you need to make sure that you use and run
a supported event loop.

%prep
%setup -q -n AnyEvent-HTTP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
%{__rm} -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
%{__rm} -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYING README
%{perl_vendorlib}/*
%{_mandir}/man3/*.3pm*

%changelog
* Tue Aug 17 2010 Tom Throckmorton <throck@mcnc.org> - 1.45-1
- update to 1.45
- minor spec changes for rebuild via mock

* Mon Jun 7 2010 Aaron Brown 1.44-1
- Update to a newer version
- Remove the custom %post scripts

* Thu Jul 09 2009 Jason Zurawski 1.4-1
- Specfile autogenerated by cpanspec 1.78.
