# Exclude this dependency it auto-picks up which is local class only needed in build
# and not included in final RPM
%global __requires_exclude perl\\(namespace::clean::_Util\\)

Name:           perl-namespace-clean
Version:        0.27
Release:        1%{?dist}
Summary:        Keep imports and functions out of your namespace
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/namespace-clean/
Source0:        namespace-clean-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-generators
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(B::Hooks::EndOfScope) >= 0.12
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Package::Stash) >= 0.23
BuildRequires:  perl(Test::More) >= 0.47
Requires:       perl(B::Hooks::EndOfScope) >= 0.12
Requires:       perl(Package::Stash) >= 0.23
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Keeping packages clean

%prep
%setup -q -n namespace-clean-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed May 17 2023 Andy Lake 0.27-1
- Specfile autogenerated by cpanspec 1.78.
