%{!?perl_prefix: %define perl_prefix %(eval "`%{__perl} -V:installprefix`"; echo $installprefix)}
%{!?perl_style: %define perl_style %(eval "`%{__perl} -V:installstyle`"; echo $installstyle)}

%define disttag pSPS

Name:           perl-Class-Fields
Version:        0.203
Release:        1.%{disttag}
Summary:        Inspect the fields of a class
License:        CHECK(GPL+ or Artistic)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Class-Fields/
Source0:        http://www.cpan.org/modules/by-module/Class/Class-Fields-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(base) >= 2
Requires:       perl(Carp)
Requires:       perl(Carp::Assert)
Requires:       perl(constant)
Requires:       perl(Test::More) >= 0.47

%description
A collection of utility functions/methods for examining the data members of
a class. It provides a nice, high-level interface that should stand the
test of time and Perl upgrades nicely.

%prep
%setup -q -n Class-Fields-%{version}

%build
%{__perl} Makefile.PL INSTALL_BASE=%{perl_prefix}
make %{?_smp_mflags}

%install
%{__rm} -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{__mv} scripts $RPM_BUILD_ROOT/tmp

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes
/usr/*
/tmp/*

%post
/tmp/./perl-Class-Fields_post.sh
%{__rm} /tmp/perl-Class-Fields_post.sh

%changelog
* Thu Aug 13 2009 Jason Zurawski 0.203-1
- Specfile autogenerated by cpanspec 1.78.
