Name:           perl-CHI
Version:        0.61
Release:        1%{?dist}
Summary:        Unified cache handling interface
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/CHI/
Source0:        CHI-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-macros
BuildRequires:  perl(Cache::FileCache)
BuildRequires:  perl(Carp::Assert) >= 0.20
BuildRequires:  perl(Class::Load)
BuildRequires:  perl(Data::UUID)
BuildRequires:  perl(Date::Parse)
BuildRequires:  perl-Digest-JHash
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec) >= 0.80
BuildRequires:  perl-Hash-MoreUtils
BuildRequires:  perl(JSON::MaybeXS) >= 1.003003
BuildRequires:  perl(List::MoreUtils) >= 0.13
BuildRequires:  perl-Log-Any >= 0.08
BuildRequires:  perl-Module-Mask
BuildRequires:  perl(Moo) >= 1.003
BuildRequires:  perl(MooX::Types::MooseLike) >= 0.23
BuildRequires:  perl(MooX::Types::MooseLike::Base)
BuildRequires:  perl-MooX-Types-MooseLike-Numeric
BuildRequires:  perl(Storable)
BuildRequires:  perl-String-RewritePrefix
BuildRequires:  perl(Task::Weaken)
BuildRequires:  perl(Test::Builder)
BuildRequires:  perl(Test::Class)
BuildRequires:  perl(Test::Deep)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Warn)
BuildRequires:  perl(Time::Duration) >= 1.06
BuildRequires:  perl(Time::Duration::Parse) >= 0.03
BuildRequires:  perl(Time::HiRes) >= 1.30
BuildRequires:  perl(Try::Tiny) >= 0.05
Requires:       perl(Carp::Assert) >= 0.20
Requires:       perl(Class::Load)
Requires:       perl(Data::UUID)
Requires:       perl-Digest-JHash
Requires:       perl(Digest::MD5)
Requires:       perl(File::Spec) >= 0.80
Requires:       perl-Hash-MoreUtils
Requires:       perl(JSON::MaybeXS) >= 1.003003
Requires:       perl(List::MoreUtils) >= 0.13
Requires:       perl-Log-Any >= 0.08
Requires:       perl(Moo) >= 1.003
Requires:       perl(MooX::Types::MooseLike) >= 0.23
Requires:       perl(MooX::Types::MooseLike::Base)
Requires:       perl-MooX-Types-MooseLike-Numeric
Requires:       perl(Storable)
Requires:       perl-String-RewritePrefix
Requires:       perl(Task::Weaken)
Requires:       perl(Time::Duration) >= 1.06
Requires:       perl(Time::Duration::Parse) >= 0.03
Requires:       perl(Time::HiRes) >= 1.30
Requires:       perl(Try::Tiny) >= 0.05
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
CHI provides a unified caching API, designed to assist a developer in
persisting data for a specified period of time.

%prep
%setup -q -n CHI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Aug 03 2022 Andrew Lake <andy@es.net> 0.61-1
- Specfile autogenerated by cpanspec 1.78.
