%{!?perl_prefix: %define perl_prefix %(eval "`%{__perl} -V:installprefix`"; echo $installprefix)}
%{!?perl_style: %define perl_style %(eval "`%{__perl} -V:installstyle`"; echo $installstyle)}

Autoreq: 0 

%define disttag pSPS

Name:           perl-AnyEvent
Version:        5.271
Release:        1.%{disttag}
Summary:        Provide framework for multiple event loops
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent/
Source0:        http://www.cpan.org/modules/by-module/AnyEvent/AnyEvent-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(JSON)
Requires:       perl(JSON::XS) >= 2.2
Requires:       perl(Net::SSLeay) >= 1.30
Requires:       coreutils
Requires:  perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
#
BuildRequires:  perl(ExtUtils::MakeMaker)

%description
AnyEvent provides an identical interface to multiple event loops. This
allows module authors to utilise an event loop without forcing module users
to use the same event loop (as only a single event loop can coexist
peacefully at any one time).

%prep
%setup -q -n AnyEvent-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
%{__rm} -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
%{__rm} -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYING README
%{perl_vendorlib}/*
%{_mandir}/man3/*.3pm*

%changelog
* Tue Aug 17 2010 Tom Throckmorton <throck@mcnc.org> - 5.271-1
- update to 5.271; 5.27 test_dynamic fails
- minor spec adjustments

* Mon Jun 7 2010 Aaron Brown 5.27-1
- Update to a newer version
- Remove the custom %post scripts

* Thu Jul 09 2009 Jason Zurawski 4.81-1
- Specfile autogenerated by cpanspec 1.78.
