#!/bin/sh

set -e -u

if [ $# -eq 0 ]
then
    printf 'Usage: %s <target-directory>\n' "$0" >&2
    exit 1
fi

here="$(dirname "$0")"
rm -rf "$here/tmp/"
./sphinx-build.py -b html "$here" "$here/tmp"
cp -f "sphinx/themes/bizstyle/static/css3-mediaqueries.js" "$1"
cp -f "sphinx/themes/scrolls/static/theme_extras.js" "$1"
cp -f "$here/tmp/_static/doctools.js" "$1"
cp -f "$here/tmp/_static/sidebar.js" "$1"
cp -f "$here/tmp/_static/searchtools.js" "$1"
rm -rf "$here/tmp/"

# vim:ts=4 sw=4 et
