Name:           perl-Net-NTP
Version:        1.5
Release:        1%{?dist}
Summary:        Perl extension for decoding NTP server responses
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-NTP/
Source0:        Net-NTP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-generators
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Time::HiRes)
BuildRequires:  perl(Test::More)
Requires:       perl(Time::HiRes)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module exports a single method (get_ntp_response) and returns an
associative array based upon RFC1305 and RFC2030. The response from the
server is "humanized" to a point that further processing of the information
received from the server can be manipulated. For example: timestamps are in
epoch, so one could use the localtime function to produce an even more
"human" representation of the timestamp.

%prep
%setup -q -n Net-NTP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue May 23 2023 Andy Lake 1.5-1
- Specfile autogenerated by cpanspec 1.78.
