Name:           perl-CGI-Session
Version:        4.48
Release:        1%{?dist}
Summary:        Persistent session data in CGI applications
License:        Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/CGI-Session/
Source0:        CGI-Session-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(CGI) >= 3.26
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Test::More)
BuildRequires:  perl-Env
Requires:       perl-Env
Requires:       perl(CGI) >= 3.26
Requires:       perl(Data::Dumper)
Requires:       perl(Digest::MD5)
Requires:       perl(Scalar::Util)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
CGI::Session provides an easy, reliable and modular session management
system across HTTP requests.

%prep
%setup -q -n CGI-Session-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changelog.ini Changes examples META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue May 16 2023 Andy Lake 4.48-1
- Specfile autogenerated by cpanspec 1.78.
