Name:           perl-Nagios-Plugin
Version:        0.36
Release:        1%{?dist}
Summary:        Family of perl modules to streamline writing Nagios plugins
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Nagios-Plugin/
Source0:        Nagios-Plugin-%{version}.tar.gz
Patch0:         Nagios-Plugin-Functions-01.t.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-macros
BuildRequires:  perl-generators
BuildRequires:  perl(Carp)
BuildRequires:  perl(Class::Accessor)
BuildRequires:  perl(Config::Tiny)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Math::Calc::Units)
BuildRequires:  perl(Params::Validate)
BuildRequires:  perl(Test::More) >= 0.62
Requires:       perl(Carp)
Requires:       perl(Class::Accessor)
Requires:       perl(Config::Tiny)
Requires:       perl(File::Spec)
Requires:       perl(Math::Calc::Units)
Requires:       perl(Params::Validate)
Requires:       perl(Test::More) >= 0.62
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Nagios::Plugin and its associated Nagios::Plugin::* modules are a family of
perl modules to streamline writing Nagios plugins. The main end user
modules are Nagios::Plugin, providing an object-oriented interface to the
entire Nagios::Plugin::* collection, and Nagios::Plugin::Functions,
providing a simpler functional interface to a useful subset of the
available functionality.

%prep
%setup -q -n Nagios-Plugin-%{version}
%patch0 -p0

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Oct 04 2023 Andy Lake<andy@es.net> 0.36-1
- Specfile autogenerated by cpanspec 1.78.
