Name:           perl-RPC-XML
Version:        0.82
Release:        1%{?dist}
Summary:        Set of classes for core data, message and XML handling
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/RPC-XML/
Source0:        RPC-XML-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008008
BuildRequires:  perl-generators
BuildRequires:  perl(Carp)
BuildRequires:  perl(DateTime)
BuildRequires:  perl(DateTime::Format::ISO8601)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Daemon)
BuildRequires:  perl(HTTP::Message)
BuildRequires:  perl(IO::Socket::IP)
BuildRequires:  perl(LWP)
BuildRequires:  perl(Module::Load)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Socket)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(XML::LibXML)
BuildRequires:  perl(XML::Parser)
Requires:       perl(Carp)
Requires:       perl(DateTime)
Requires:       perl(DateTime::Format::ISO8601)
Requires:       perl(HTTP::Daemon)
Requires:       perl(HTTP::Message)
Requires:       perl(LWP)
Requires:       perl(Module::Load)
Requires:       perl(Scalar::Util)
Requires:       perl(Socket)
Requires:       perl(XML::LibXML)
Requires:       perl(XML::Parser)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The RPC::XML package is an implementation of the XML-RPC standard. The
package as a whole provides classes for data, for clients, for servers and
for parsers (based on the XML::Parser and XML::LibXML packages from CPAN).

%prep
%setup -q -n RPC-XML-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog ChangeLog.xml META.json perlcritic.rc README README.apache2
%{perl_vendorlib}/*
%{_bindir}/*
%{_mandir}/man3/*
%{_mandir}/man1/*

%changelog
* Tue May 16 2023 Andy Lake 0.82-1
- Specfile autogenerated by cpanspec 1.78.
