#!/bin/sh
set -e -u
cp -r tests "$ADTTMP/"
cd "$ADTTMP"
py3versions -i \
| tr ' ' '\n' \
| xargs -I {} env PYTHONWARNINGS=d PYTHONHASHSEED=random {} \
  tests/run.py --verbose 2>&1

# vim:ts=4 sw=4 et
