Name:           perl-Params-Validate
Version:        1.31
Release:        1%{?dist}
Summary:        Validate method/function parameters
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Params-Validate/
Source0:        Params-Validate-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(Carp)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::Implementation)
BuildRequires:  perl(Scalar::Util) >= 1.10
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(Test::Requires)
BuildRequires:  gcc
BuildRequires:  perl-generators
Requires:       perl(Carp)
Requires:       perl(Exporter)
Requires:       perl(Module::Implementation)
Requires:       perl(Scalar::Util) >= 1.10
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
I would recommend you consider using Params::ValidationCompiler instead.
That module, despite being pure Perl, is significantly faster than this
one, at the cost of having to adopt a type system such as Specio,
Type::Tiny, or the one shipped with Moose.

%prep
%setup -q -n Params-Validate-%{version}

%build
%{__perl} Build.PL installdirs=vendor optimize="$RPM_OPT_FLAGS"
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc azure-pipelines.yml Changes CODE_OF_CONDUCT.md CONTRIBUTING.md cpanfile dist.ini LICENSE META.json perlcriticrc perltidyrc README.md tidyall.ini TODO weaver.ini
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Params*
%{_mandir}/man3/*

%changelog
* Mon May 15 2023 Andy Lake 1.31-1
- Specfile autogenerated by cpanspec 1.78.