%{!?perl_prefix: %define perl_prefix %(eval "`%{__perl} -V:installprefix`"; echo $installprefix)}
%{!?perl_style: %define perl_style %(eval "`%{__perl} -V:installstyle`"; echo $installstyle)}

%define disttag pSPS

Name:           perl-Net-CIDR
Version:        0.13
Release:        1.%{disttag}
Summary:        Manipulate IPv4/IPv6 netblocks in CIDR notation
License:        Distributable, see COPYING
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-CIDR/
Source0:        http://www.cpan.org/modules/by-module/Net/Net-CIDR-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Requires:       perl(Carp)
Requires:       perl

%description
The Net::CIDR package contains functions that manipulate lists of IP
netblocks expressed in CIDR notation. The Net::CIDR functions handle both
IPv4 and IPv6 addresses.

%prep
%setup -q -n Net-CIDR-%{version}

%build
%{__perl} Makefile.PL INSTALL_BASE=%{perl_prefix}
make %{?_smp_mflags}

%install
%{__rm} -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{__mv} scripts $RPM_BUILD_ROOT/tmp

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
%{__rm} -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYING Net-CIDR.spec README
/usr/*
/tmp/*

%post
/tmp/./perl-Net-CIDR_post.sh
%{__rm} /tmp/perl-Net-CIDR_post.sh

%changelog
* Thu Jul 09 2009 Jason Zurawski 0.13-1
- Specfile autogenerated by cpanspec 1.78.
