Name:           perl-common-sense
Version:        3.75
Release:        1%{?dist}
Summary:        Save a tree AND a kitten, use common::sense!
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/common-sense/
Source0:        common-sense-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl-generators
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
“Nothing is more fairly distributed than common sense: no one thinks   he
needs more of it than he already has.”

%prep
%setup -q -n common-sense-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README
%{perl_vendorarch}/*
%{_mandir}/man3/*

%changelog
* Tue May 16 2023 Andy Lake 3.75-1
- Specfile autogenerated by cpanspec 1.78.
