Name:           perl-Sys-Statistics-Linux
Version:        0.59
Release:        3%{?dist}
Summary:        Front-end module to collect system statistics
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Sys-Statistics-Linux/
Source0:        http://www.cpan.org//authors/id/B/BL/BLOONIX/Sys-Statistics-Linux-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(UNIVERSAL::require)
BuildRequires:  perl(POSIX)
BuildRequires:  perl(Test::Pod)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod::Coverage)
BuildRequires:  perl(Time::HiRes)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))


%description
Sys::Statistics::Linux is a front-end module and gather different linux
system information like processor workload, memory usage, network and disk
statistics and a lot more. Refer the documentation of the distribution
modules to get more information about all possible statistics.


%prep
%setup -q -n Sys-Statistics-Linux-%{version}


%build
%{__perl} Build.PL installdirs=vendor
./Build


%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*


%check
./Build test


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc ChangeLog LICENCE README
%{perl_vendorlib}/*
%{_mandir}/man3/*


%changelog
* Tue Dec 14 2010 Lubomir Rintel (GoodData) <lubo.rintel@gooddata.com> 0.59-3
- Drag Time::HiRes in BR

* Tue Dec 14 2010 Lubomir Rintel (GoodData) <lubo.rintel@gooddata.com> 0.59-2
- Spelling fix

* Sun Dec 12 2010 Lubomir Rintel (GoodData) <lubo.rintel@gooddata.com> 0.59-1
- Run tests
- Later release

* Fri Nov 26 2010 Lubomir Rintel (GoodData) <lubo.rintel@gooddata.com> 0.42-2
- BR Test::More

* Mon Oct 06 2008 Lubomir Rintel (Good Data) <lubo.rintel@gooddata.com> 0.42-1
- Specfile autogenerated by cpanspec 1.77.
- Fixed build-time requires
