#!/bin/bash
#
# Init file for perfSONAR TL1 Alarms Collector Daemon
#
# chkconfig: 2345 60 20
# description: perfSONAR TL1 Alarms Collector Daemon
#

PREFIX=/opt/perfsonar_ps/alarms
BINDIR=${PREFIX}/bin
CONFDIR=${PREFIX}/etc
RUNDIR=/var/run

CONFFILE=${CONFDIR}/collector.conf
LOGGERFILE=${CONFDIR}/collector-logger.conf
PIDFILE=${RUNDIR}/collector.pid

USER=perfsonar
GROUP=perfsonar

PERFSONAR="${BINDIR}/daemon.pl --config=${CONFFILE} --pidfile=${PIDFILE} --logger=${LOGGERFILE} --user=${USER} --group=${GROUP}"

ERROR=0
ARGV="$@"
if [ "x$ARGV" = "x" ] ; then 
    ARGS="help"
fi

for ARG in $@ $ARGS
do
    # check for pidfile
    if [ -f $PIDFILE ] ; then
        PID=`cat $PIDFILE`
        if [ "x$PID" != "x" ] && kill -0 $PID 2>/dev/null ; then
            STATUS="TL1 Alarms Collector (pid $PID) running"
            RUNNING=1
        else
            STATUS="TL1 Alarms Collector (pid $PID?) not running"
            RUNNING=0
        fi
    else
        STATUS="TL1 Alarms Collector (no pid file) not running"
        RUNNING=0
    fi 

    case $ARG in
    start)
	echo $PERFSONAR

	if $PERFSONAR ; then
	    echo "$0 $ARG: TL1 Alarms Collector started"
            touch /var/lock/subsys/alarms_collector
	else
	    echo "$0 $ARG: TL1 Alarms Collector could not be started"
	    ERROR=3
	fi
	;;
    stop)
	if [ $RUNNING -eq 0 ]; then
	    echo "$0 $ARG: $STATUS"
	    continue
	fi
	if kill $PID ; then
	    echo "$0 $ARG: TL1 Alarms Collector stopped"
            rm /var/lock/subsys/alarms_collector
	else
	    echo "$0 $ARG: TL1 Alarms Collector could not be stopped"
	    ERROR=4
	fi
	;;
    restart)
    	$0 stop; echo "waiting..."; sleep 10; $0 start;
	;;
    *)
	echo "usage: $0 (start|stop|restart|help)"
	cat <<EOF

start      - start TL1 Alarms Collector
stop       - stop TL1 Alarms Collector
restart    - restart TL1 Alarms Collector if running by sending a SIGHUP or start if 
             not running
help       - this screen

EOF
	ERROR=2
    ;;

    esac

done

exit $ERROR
